### PR TITLE
PHP SDK: hello world

### PR DESCRIPTION
**Pull request by seregazhuk**
Draft for PHP SDK "Hello world" section.

### CODE REVIEW

**Comment by sw-yx** [comment]
@docs team - just note that this is still draft - Sergey isnt done writing it yet

**Comment by sw-yx** [comment]
re-ping @seregazhuk on the status of this

**Comment by seregazhuk** [comment]
@sw-yx I'have pushed the latest fixes. I think it is ready for review. What should I do next?

**Comment by flossypurse** [comment]
So, don't get me wrong - there is a lot of great stuff in here, particularly for the PHP docs.
But feedback on our "Hello World!" tutorials has not been super great - 
Basically they are barely a step up from cloning the running examples in the samples repo.

I want to be transparent that sometime in the very near future we may be completely overhauling the "Run you first app" & "Hello World" tutorials into some sort of "Getting Started - Learning Path".

**Comment by sw-yx** [comment]
merging while acknowledging Cullys feedback which i agree with

**Pull request merged**
