### PR TITLE
[chore] update algolia key to new app, enable faceting

### PR DESCRIPTION
**Pull request by sw-yx**
## What does this PR do?

[chore] update algolia key to new app, enable faceting

### CODE REVIEW

**Comment by sw-yx** [comment]
theoretically there is supposed to be faceting enabled:

image

but i cant get the actual facet options to display when i search and the docs aren't very helpful  :( cc @slorber in case you want feedback on faceted search with algolia

resources used: 
- https://docusaurus.io/docs/search#contextual-search
- https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/how-to/declaring-attributes-for-faceting/?client=javascript
- https://discourse.algolia.com/t/how-to-configure-a-new-facet/10776/9

still the results better than before so recommend merging

**Comment by slorber** [comment]
Not sure to understand what you want me to check? 🤔 

FYI we enabled contextualSearch by default recently, maybe you now want to disable it?

**Comment by sw-yx** [comment]
@slorber we were unable to enable faceted search in docusaurus, even though i enabled facet index in algolia, i have not seen any docs or examples or screenshots that show that docusaurus has faceted search... is that something that comes in the docusaurus search component, or do we have to code it ourselves?

**Comment by slorber** [comment]
@sw-yx all sites with `contextualSearch: true` (now the default in beta 15) are using facetFilters search, officially documented as `searchParameters.facetFilters` on the DocSearch/Algolia docs that we reference from our doc.

image

(there's a typo in that example that I'm fixing in https://github.com/facebook/docusaurus/pull/6704)

The way it works: we merge the contextual facetFilters (dynamic, depends on current page) with the ones you provide in config.

If `contextualSearch: true` does not work for you it's likely hiding a deeper problem. Maybe @shortcuts can help figure it out.

Now, when you say "faceted search", are you talking about filtering (ie `facetFilcers`) or do you have something else in mind?

**Comment by shortcuts** [comment]
Hey

@sw-yx you can go to the edit -> `search preview` and see that only `docusaurus_tag` was retrieved during last crawl (feb 15), which makes `contextualSearch` unusable as it's missing `language`.

We hint this issue in our UI with the following error, (we might need to display it somewhere else too 🤔)
Screenshot 2022-02-17 at 12 13 47

As you've edited the `indexSettings` in the Algolia dashboard, restarting the crawl should be enough, but otherwise deleting the index and starting a new crawl will also solve it.

**Pull request merged**
