### PR TITLE
Use more common form of continue_as_new

### PR DESCRIPTION
**Pull request by lorensr**

### CODE REVIEW

**Comment by lorensr** [comment]
See: https://www.google.com/url?q=https://github.com/temporalio/samples-python/blob/82f5267edeeedbe868e5ce2bcdacdc21d068be02/hello/hello_continue_as_new.py%23L17&sa=D&source=docs&ust=1686169650445879&usg=AOvVaw0uq6AdnVyJzaoreSf20HWR

**Review by cretz — APPROVED** [review]
Though I mildly regret ever making this available instead of requiring that a workflow reference be given every time for type-safety reasons, even though 99% of the time it's the same workflow. In .NET I did not make that mistake (continue as new doesn't have implicit "my same workflow type", you _have_ to provide it for workflow input type safety reasons).

**Comment by lorensr** [comment]
we could change this & sample to reference workflow, to recommend type
safety?

**Review by DJSanti — APPROVED** [review]

**Comment by DJSanti** [comment]
@lorensr please resolve the conflict and merge.

**Review by DJSanti — CHANGES_REQUESTED** [review]
Get this branch back on track with main. This will clear up the merge conflicts.

Per Cully:
if you have branch x - and you need to merge main into it - and fix conflicts ... do the following:
ON branch-x
git pull origin branch-x
so you have all the latest stuff from your own branch.
git checkout main
git fetch && git pull origin main
now you have all the latest stuff in main
git checkout branch-x
git merge main
Now fix the conflicts - make sure there is a clean build
most of the conflicts docs dir are resolved automatically by running Assembly
so do that
yarn assemble
yarn format
yarn build
Now, git add . && git commit -m "merging main"
git push origin branch-x

**Comment by lorensr** [comment]
This has been fixed in the dacx snippet currently in use: https://github.com/temporalio/documentation-samples-python/blob/main/continue_as_new/your_workflows_dacx.py

**Pull request closed without merging**
