### PR TITLE
Adding new workflow id conflict policy page and updating subsequent pages

### PR DESCRIPTION
**Pull request by jsundai**
Picked up work from https://github.com/temporalio/documentation/pull/2698 
This content is waiting on [Temporal Server v1.24 release](https://github.com/temporalio/temporal)

Internal tracking: JIRA EDU-2155

https://github.com/temporalio/features/issues/437

### CODE REVIEW

**Review by flossypurse — APPROVED** [review]

**Comment by flossypurse** [comment]
@stephanos We did some IA refactoring and decided to just pick up your content contribution from here: https://github.com/temporalio/documentation/pull/2698

Can you review this PR at your convenience?

**Review by stephanos — APPROVED** [review]
LGTM!

**Comment by stephanos** [comment]
@flossypurse this PR is now unblocked as [we released the new Go version](https://github.com/temporalio/sdk-go/releases/tag/v1.29.0) that includes this capability and the new API that makes use of it.

**Comment by stephanos** [comment]
@jsundai this PR is now unblocked as [we released the new Go version](https://github.com/temporalio/sdk-go/releases/tag/v1.29.0) that includes this capability and the new API that makes use of it.

**Review by stephanos — APPROVED** [review]

**Comment by jsundai** [comment]
Thanks, @stephanos :raised_hands:

**Pull request merged**
