### PR TITLE
 Update host verification flag

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

## What was changed:

update the tls host verification flag 
## Why?

https://github.com/temporalio/temporal/pull/1478
## Checklist

1. Closes issue: 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Comment by tsurdilo** [comment]
@flossypurse This change should take effect with Temporal 1.9. We should not merge it before. 

depends on https://github.com/temporalio/temporal/pull/1478

**Review by rylandg — APPROVED** [review]
LGTM

**Review by flossypurse — APPROVED** [review]

**Comment by sw-yx** [comment]
@tsurdilo looks like theres a merge conflict, otherwise this is mergeable

**Comment by tsurdilo** [comment]
@sw-yx rebased

**Pull request merged**
