### PR TITLE
Update SDK logos and spacing

### PR DESCRIPTION
**Pull request by feedmeapples**
## What does this PR do?
- Replaced SDK logos to clean the look (not strong opinion)
- Set logo sizes through css instead of native image size
- Add spacing between SDKs in mobile view

image

before -> after (small width view)
image

### CODE REVIEW

**Comment by feedmeapples** [comment]
not picky for node sdk logo, "JS" seems to fit the page nicer. As well as the other logos. Mostly a proposal for changes @sw-yx

**Review by flossypurse — APPROVED** [review]
I am good with it.
Thanks @feedmeapples !

**Comment by flossypurse** [comment]
Screen Shot 2021-07-19 at 7 43 02 AM

Though this looks pretty uneven now -

**Comment by feedmeapples** [comment]
> Screen Shot 2021-07-19 at 7 43 02 AM
> 
> Though this looks pretty uneven now -

could you add details, what browser this is?

**Comment by flossypurse** [comment]
> > Screen Shot 2021-07-19 at 7 43 02 AM
> > Though this looks pretty uneven now -
> 
> could you add details, what browser is this?

Chrome, but its the main landing page when you click "Run your first app".
That feature uses the same logos.

**Review by sw-yx — APPROVED** [review]

**Pull request merged**
