### PR TITLE
EDU-3361: Align Python and Go with .NET Workflow Init

### PR DESCRIPTION
**Pull request by fairlydurable**
- Brings feature explanation to the first line.
- Removes parentheticals.
- Minor adjustments.

### CODE REVIEW

**Comment by fairlydurable** [comment]
@dandavison @Quinn-With-Two-Ns Please check that no technical information was compromised with the .NET alignment. Thanks.

**Review by dandavison — CHANGES_REQUESTED** [review]
I don't think this change is an improvement. In particular, this line

> The `@workflow.init` decorator method gives message handlers access to [Workflow input]

is more confusing than what exists currently. It gives the _constructor_ access; users already have a way to give message handlers access.

The point that we're trying to convey is

1. In Java/Python/.NET there's a way to make your _constructor_ receive the workflow input, in addition to the workflow run method.

2. This is useful because there's a non-obvious pitfall with Temporal: it's possible for a message handler to execute before the first line of your workflow has run.

**Comment by fairlydurable** [comment]
@dandavison Would specifying 

> The @workflow.init decorator method gives message handler constructors/initializers access to [Workflow input]

work?

**Comment by dandavison** [comment]
> The @workflow.init decorator method gives message handler constructors/initializers access to [Workflow input]

I find the current version of the Python and Java docs to make the point more clearly than variants of this PR. (Perhaps that means I'd support making .NET the same as them)

**Comment by fairlydurable** [comment]
Closing the ticket. SDK does not have confidence in changes.

**Pull request closed without merging**
