### PR TITLE
update the production dependencies section with correct info

### PR DESCRIPTION
**Pull request by idoshamun**
## What does this PR do?

After some digging, we found the root cause for my previous issue.
You can find more information in my comment here:
https://github.com/temporalio/sdk-typescript/issues/489#issuecomment-1046246332

### CODE REVIEW

**Comment by sw-yx** [comment]
not sure if this is a specific recommendation we want to give as prebuilding workflows is meant to be a performance optimization. cc @lorensr if this is a dependency that we should pull in then lets do that, its just acorn so i imagine pretty light

**Comment by lorensr** [comment]
Yeah, we don't want to force use of `workflowBundle` or `npm i --production=false` in prod. I updated the issue: https://github.com/temporalio/sdk-typescript/issues/489#issuecomment-1048250793

For now, let's continue with the `npm i` recommendation. I updated `--production=false` and added a link to the issue.

**Comment by idoshamun** [comment]
Ok makes sense. @sw-yx should I go ahead and close this PR then?

**Comment by sw-yx** [comment]
no no, Loren updated the doc for you. @flossypurse can you stamp?

**Review by flossypurse — APPROVED** [review]

**Pull request merged**
