### PR TITLE
upgrade docusaurus to beta.6

### PR DESCRIPTION
**Pull request by sw-yx**
## What does this PR do?

testgin the latest from @slorber https://twitter.com/docusaurus/status/1433463372666789892

### CODE REVIEW

**Comment by flossypurse** [comment]
Looks like some issues with the go & java hello world tutorials meta data needs to get fixed along with this.

**Comment by sw-yx** [comment]
i also filed an issue with docusaurus as i'm not sure if this is a breaking change

**Comment by sw-yx** [comment]
per https://github.com/facebook/docusaurus/issues/5478#issuecomment-912118520, we are in the wrong and should change it on our end

**Comment by flossypurse** [comment]
should be able to rebase and get a clean build now.

**Review by flossypurse — APPROVED** [review]

**Pull request merged**
